services:
    avathar.bbguildlotro.installer:
        class: avathar\bbguildlotro\game\lotro_installer
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@config'
            - '@user'

    avathar.bbguildlotro.provider:
        class: avathar\bbguildlotro\game\lotro_provider
        arguments:
            - '@avathar.bbguildlotro.installer'
            - '@ext.manager'
        tags:
            - { name: bbguild.game_provider }
